FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY data/ data/
COPY .env .

ENV MLFLOW_TRACKING_URI=http://mlflow-server:5000

CMD ["python3", "src/train.py"]